Add container host to MQTT events
miaucl/docker2mqtt pull request #30
Opened 2024-12-18 22:53 UTC by mscottco

Hope it's okay to open a pull request against your repo. This change is to add the container host to the MQTT events so it appears as an attribute in Homeassistant so its a bit easier to tell which containers are running where...

2024-12-19 07:32 UTC, miaucl commented
> Hope it's okay to open a pull request against your repo. This change is to add the container host to the MQTT events so it appears as an attribute in Homeassistant so its a bit easier to tell which containers are running where...

Not sure why you would need this info in the event? The discovery topic should already contain the relevant information and can be used to identify the server. I'd prefer to avoid adding data to the event, which is redundant and just increases bandwidth for mqtt.

2024-12-19 07:34 UTC, miaucl commented
Information available in the discovery topic

```
{"name": "CPU", "unique_id": "docker_homeserver_homeassistant/sensor/docker/homeserver_docker2mqtt_cpu_stats/config", "availability_topic": "docker/homeserver/status", "payload_available": "online", "payload_not_available": "offline", "state_topic": "docker/homeserver/docker2mqtt/stats", "value_template": "{{ value_json.cpu if value_json is not undefined and value_json.cpu is not undefined else None }}", "unit_of_measurement": "%", "icon": "mdi:chip", "device": {"identifiers": "homeserver_docker_docker2mqtt", "name": "homeserver Docker docker2mqtt", "model": "Linux x86_64 Docker version 27.2.1, build 9e34c9b"}, "qos": 1}
```

What is your usecase which is not covered by this?

2025-01-05 23:54 UTC, mscottco commented
Thanks, Totally understand wanting to keep the MQTT payloads light.

The main use case is that I've got the entities fed into a flex-table-card in homeassistant and it's useful to be able to sort+filter based on the host they're running on. I agree the data is in the friendly_name of the entity but its not an easy or clean field to present the data with.

2025-01-06 15:54 UTC, miaucl approved these changes
This is reasonable I guess :)

2025-01-06 16:02 UTC, miaucl commented
@mscottco Please check with the workflows that the types are correctly set.

2025-01-20 14:39 UTC, miaucl requested changes

2025-01-20 14:39 UTC, miaucl commented on docker2mqtt/type_definitions.py
> +    host: str | None
does that have to be optional? Default conf does source it from `socket.gethostname()` and it should therefore be set all the time in `cfg['docker2mqtt_hostname']` (see type: `Docker2MqttConfig`).

2025-01-21 03:47 UTC, mscottco commented on docker2mqtt/type_definitions.py
> +    host: str | None
You're correct, my mistake sorry

2025-01-21 05:40 UTC, miaucl requested changes
Did you run the mypy task locally in your repo?

2025-09-26 22:18 UTC, closed without merging